// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pggen

import (
	"database/sql"
)

type Account struct {
	ID             string
	Username       string
	Pwhash         string
	Role           string
	SessionID      sql.NullString
	SessionCreated sql.NullInt64
	CreatedAt      int64
	LastLogin      sql.NullInt64
}

type ApiKey struct {
	ID        string
	AccountID string
	Name      string
	Prefix    string
	Hash      string
	Role      string
	CreatedAt int64
	LastUsed  sql.NullInt64
}

type Device struct {
	ID           string
	Username     string
	Caption      sql.NullString
	Type         string
	LastActivity sql.NullInt64
}

type Episode struct {
	Username    string
	Device      sql.NullString
	Podcast     string
	Episode     string
	Timestamp   sql.NullInt64
	Guid        sql.NullString
	Action      string
	Started     sql.NullInt64
	Position    sql.NullInt64
	Total       sql.NullInt64
	Modified    int64
	ContentHash string
}

type Setting struct {
	Key   string
	Value string
}

type Subscription struct {
	Username string
	Url      string
	Created  int64
	Deleted  sql.NullInt64
}

type User struct {
	Username       string
	Pwhash         string
	SessionID      sql.NullString
	SessionCreated sql.NullInt64
	AccountID      string
	LastActivity   sql.NullInt64
	ShareToken     sql.NullString
}
