// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pggen

import (
	"context"
	"database/sql"
)

const addSubscription = `-- name: AddSubscription :exec
INSERT INTO subscriptions (username, url, created)
VALUES ($1, $2, $3)
ON CONFLICT(url, username) DO UPDATE SET
    created = CASE WHEN subscriptions.deleted IS NOT NULL THEN EXCLUDED.created ELSE subscriptions.created END,
    deleted = NULL
`

type AddSubscriptionParams struct {
	Username string
	Url      string
	Created  int64
}

func (q *Queries) AddSubscription(ctx context.Context, arg AddSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, addSubscription, arg.Username, arg.Url, arg.Created)
	return err
}

const countAPIKeysByAccount = `-- name: CountAPIKeysByAccount :one
SELECT COUNT(*) FROM api_keys WHERE account_id = $1
`

func (q *Queries) CountAPIKeysByAccount(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAPIKeysByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) FROM accounts
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveSubscriptions = `-- name: CountActiveSubscriptions :one
SELECT COUNT(*) FROM subscriptions WHERE deleted IS NULL
`

func (q *Queries) CountActiveSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDevices = `-- name: CountDevices :one
SELECT COUNT(*) FROM devices
`

func (q *Queries) CountDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEpisodes = `-- name: CountEpisodes :one
SELECT COUNT(*) FROM episodes
`

func (q *Queries) CountEpisodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEpisodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

// Stats
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, account_id, name, prefix, hash, role, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAPIKeyParams struct {
	ID        string
	AccountID string
	Name      string
	Prefix    string
	Hash      string
	Role      string
	CreatedAt int64
}

// API Keys
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.Prefix,
		arg.Hash,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, username, pwhash, role, created_at) VALUES ($1, $2, $3, $4, $5)
`

type CreateAccountParams struct {
	ID        string
	Username  string
	Pwhash    string
	Role      string
	CreatedAt int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.Username,
		arg.Pwhash,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (id, username, caption, type) VALUES ($1, $2, $3, $4)
ON CONFLICT (id, username) DO NOTHING
`

type CreateDeviceParams struct {
	ID       string
	Username string
	Caption  sql.NullString
	Type     string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.Username,
		arg.Caption,
		arg.Type,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, pwhash, account_id) VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	Username  string
	Pwhash    string
	AccountID string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.Pwhash, arg.AccountID)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1 AND account_id = $2
`

type DeleteAPIKeyParams struct {
	ID        string
	AccountID string
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, arg.ID, arg.AccountID)
	return err
}

const deleteAPIKeysByAccount = `-- name: DeleteAPIKeysByAccount :exec
DELETE FROM api_keys WHERE account_id = $1
`

func (q *Queries) DeleteAPIKeysByAccount(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKeysByAccount, accountID)
	return err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteAllUserDevices = `-- name: DeleteAllUserDevices :exec
DELETE FROM devices WHERE username = $1
`

func (q *Queries) DeleteAllUserDevices(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserDevices, username)
	return err
}

const deleteAllUserEpisodes = `-- name: DeleteAllUserEpisodes :exec
DELETE FROM episodes WHERE username = $1
`

func (q *Queries) DeleteAllUserEpisodes(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserEpisodes, username)
	return err
}

const deleteAllUserSubscriptions = `-- name: DeleteAllUserSubscriptions :exec
DELETE FROM subscriptions WHERE username = $1
`

func (q *Queries) DeleteAllUserSubscriptions(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserSubscriptions, username)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1 AND username = $2
`

type DeleteDeviceParams struct {
	ID       string
	Username string
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, arg.ID, arg.Username)
	return err
}

const deleteEpisodesOlderThan = `-- name: DeleteEpisodesOlderThan :execresult
DELETE FROM episodes WHERE modified < $1
`

func (q *Queries) DeleteEpisodesOlderThan(ctx context.Context, modified int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEpisodesOlderThan, modified)
}

const deleteSubscription = `-- name: DeleteSubscription :exec
UPDATE subscriptions SET deleted = $1
WHERE username = $2 AND url = $3 AND deleted IS NULL
`

type DeleteSubscriptionParams struct {
	Deleted  sql.NullInt64
	Username string
	Url      string
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, arg.Deleted, arg.Username, arg.Url)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, username)
	return err
}

const deleteUsersByAccount = `-- name: DeleteUsersByAccount :exec
DELETE FROM users WHERE account_id = $1
`

func (q *Queries) DeleteUsersByAccount(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, deleteUsersByAccount, accountID)
	return err
}

const getAPIKeysByPrefix = `-- name: GetAPIKeysByPrefix :many
SELECT id, account_id, name, prefix, hash, role, created_at, last_used FROM api_keys WHERE prefix = $1
`

func (q *Queries) GetAPIKeysByPrefix(ctx context.Context, prefix string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, getAPIKeysByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.Role,
			&i.CreatedAt,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, pwhash, role, session_id FROM accounts WHERE id = $1
`

type GetAccountByIDRow struct {
	ID        string
	Username  string
	Pwhash    string
	Role      string
	SessionID sql.NullString
}

// Accounts
func (q *Queries) GetAccountByID(ctx context.Context, id string) (GetAccountByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Pwhash,
		&i.Role,
		&i.SessionID,
	)
	return i, err
}

const getAccountBySession = `-- name: GetAccountBySession :one
SELECT id, username, pwhash, role, session_id, session_created FROM accounts WHERE session_id = $1
`

type GetAccountBySessionRow struct {
	ID             string
	Username       string
	Pwhash         string
	Role           string
	SessionID      sql.NullString
	SessionCreated sql.NullInt64
}

func (q *Queries) GetAccountBySession(ctx context.Context, sessionID sql.NullString) (GetAccountBySessionRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountBySession, sessionID)
	var i GetAccountBySessionRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Pwhash,
		&i.Role,
		&i.SessionID,
		&i.SessionCreated,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, pwhash, role, session_id FROM accounts WHERE username = $1
`

type GetAccountByUsernameRow struct {
	ID        string
	Username  string
	Pwhash    string
	Role      string
	SessionID sql.NullString
}

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (GetAccountByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUsername, username)
	var i GetAccountByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Pwhash,
		&i.Role,
		&i.SessionID,
	)
	return i, err
}

const getEpisodes = `-- name: GetEpisodes :many
SELECT username, device, podcast, episode, timestamp, guid, action,
       started, position, total, modified
FROM episodes
WHERE username = $1 AND modified >= $2
`

type GetEpisodesParams struct {
	Username string
	Modified int64
}

type GetEpisodesRow struct {
	Username  string
	Device    sql.NullString
	Podcast   string
	Episode   string
	Timestamp sql.NullInt64
	Guid      sql.NullString
	Action    string
	Started   sql.NullInt64
	Position  sql.NullInt64
	Total     sql.NullInt64
	Modified  int64
}

// Episodes
func (q *Queries) GetEpisodes(ctx context.Context, arg GetEpisodesParams) ([]GetEpisodesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEpisodes, arg.Username, arg.Modified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEpisodesRow
	for rows.Next() {
		var i GetEpisodesRow
		if err := rows.Scan(
			&i.Username,
			&i.Device,
			&i.Podcast,
			&i.Episode,
			&i.Timestamp,
			&i.Guid,
			&i.Action,
			&i.Started,
			&i.Position,
			&i.Total,
			&i.Modified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEpisodesByDevice = `-- name: GetEpisodesByDevice :many
SELECT username, device, podcast, episode, timestamp, guid, action,
       started, position, total, modified
FROM episodes
WHERE username = $1 AND device = $2 AND modified >= $3
`

type GetEpisodesByDeviceParams struct {
	Username string
	Device   sql.NullString
	Modified int64
}

type GetEpisodesByDeviceRow struct {
	Username  string
	Device    sql.NullString
	Podcast   string
	Episode   string
	Timestamp sql.NullInt64
	Guid      sql.NullString
	Action    string
	Started   sql.NullInt64
	Position  sql.NullInt64
	Total     sql.NullInt64
	Modified  int64
}

func (q *Queries) GetEpisodesByDevice(ctx context.Context, arg GetEpisodesByDeviceParams) ([]GetEpisodesByDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, getEpisodesByDevice, arg.Username, arg.Device, arg.Modified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEpisodesByDeviceRow
	for rows.Next() {
		var i GetEpisodesByDeviceRow
		if err := rows.Scan(
			&i.Username,
			&i.Device,
			&i.Podcast,
			&i.Episode,
			&i.Timestamp,
			&i.Guid,
			&i.Action,
			&i.Started,
			&i.Position,
			&i.Total,
			&i.Modified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEpisodesByPodcast = `-- name: GetEpisodesByPodcast :many
SELECT username, device, podcast, episode, timestamp, guid, action,
       started, position, total, modified
FROM episodes
WHERE username = $1 AND podcast = $2 AND modified >= $3
`

type GetEpisodesByPodcastParams struct {
	Username string
	Podcast  string
	Modified int64
}

type GetEpisodesByPodcastRow struct {
	Username  string
	Device    sql.NullString
	Podcast   string
	Episode   string
	Timestamp sql.NullInt64
	Guid      sql.NullString
	Action    string
	Started   sql.NullInt64
	Position  sql.NullInt64
	Total     sql.NullInt64
	Modified  int64
}

func (q *Queries) GetEpisodesByPodcast(ctx context.Context, arg GetEpisodesByPodcastParams) ([]GetEpisodesByPodcastRow, error) {
	rows, err := q.db.QueryContext(ctx, getEpisodesByPodcast, arg.Username, arg.Podcast, arg.Modified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEpisodesByPodcastRow
	for rows.Next() {
		var i GetEpisodesByPodcastRow
		if err := rows.Scan(
			&i.Username,
			&i.Device,
			&i.Podcast,
			&i.Episode,
			&i.Timestamp,
			&i.Guid,
			&i.Action,
			&i.Started,
			&i.Position,
			&i.Total,
			&i.Modified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEpisodesByPodcastAndDevice = `-- name: GetEpisodesByPodcastAndDevice :many
SELECT username, device, podcast, episode, timestamp, guid, action,
       started, position, total, modified
FROM episodes
WHERE username = $1 AND podcast = $2 AND device = $3 AND modified >= $4
`

type GetEpisodesByPodcastAndDeviceParams struct {
	Username string
	Podcast  string
	Device   sql.NullString
	Modified int64
}

type GetEpisodesByPodcastAndDeviceRow struct {
	Username  string
	Device    sql.NullString
	Podcast   string
	Episode   string
	Timestamp sql.NullInt64
	Guid      sql.NullString
	Action    string
	Started   sql.NullInt64
	Position  sql.NullInt64
	Total     sql.NullInt64
	Modified  int64
}

func (q *Queries) GetEpisodesByPodcastAndDevice(ctx context.Context, arg GetEpisodesByPodcastAndDeviceParams) ([]GetEpisodesByPodcastAndDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, getEpisodesByPodcastAndDevice,
		arg.Username,
		arg.Podcast,
		arg.Device,
		arg.Modified,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEpisodesByPodcastAndDeviceRow
	for rows.Next() {
		var i GetEpisodesByPodcastAndDeviceRow
		if err := rows.Scan(
			&i.Username,
			&i.Device,
			&i.Podcast,
			&i.Episode,
			&i.Timestamp,
			&i.Guid,
			&i.Action,
			&i.Started,
			&i.Position,
			&i.Total,
			&i.Modified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = $1
`

// Settings
func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getSubscriptions = `-- name: GetSubscriptions :many
SELECT url FROM subscriptions WHERE username = $1 AND deleted IS NULL
`

// Subscriptions
func (q *Queries) GetSubscriptions(ctx context.Context, username string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptions, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsSince = `-- name: GetSubscriptionsSince :many
SELECT url, CASE WHEN deleted IS NULL THEN 0 ELSE 1 END AS is_deleted
FROM subscriptions
WHERE username = $1 AND (created >= $2 OR deleted >= $3)
`

type GetSubscriptionsSinceParams struct {
	Username string
	Created  int64
	Deleted  sql.NullInt64
}

type GetSubscriptionsSinceRow struct {
	Url       string
	IsDeleted int32
}

func (q *Queries) GetSubscriptionsSince(ctx context.Context, arg GetSubscriptionsSinceParams) ([]GetSubscriptionsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsSince, arg.Username, arg.Created, arg.Deleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubscriptionsSinceRow
	for rows.Next() {
		var i GetSubscriptionsSinceRow
		if err := rows.Scan(&i.Url, &i.IsDeleted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT username, pwhash, session_id, account_id, last_activity, share_token FROM users WHERE username = $1
`

type GetUserRow struct {
	Username     string
	Pwhash       string
	SessionID    sql.NullString
	AccountID    string
	LastActivity sql.NullInt64
	ShareToken   sql.NullString
}

// Users (gPodder API)
func (q *Queries) GetUser(ctx context.Context, username string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i GetUserRow
	err := row.Scan(
		&i.Username,
		&i.Pwhash,
		&i.SessionID,
		&i.AccountID,
		&i.LastActivity,
		&i.ShareToken,
	)
	return i, err
}

const getUserBySession = `-- name: GetUserBySession :one
SELECT username, pwhash, session_id, session_created, account_id, last_activity FROM users WHERE session_id = $1
`

type GetUserBySessionRow struct {
	Username       string
	Pwhash         string
	SessionID      sql.NullString
	SessionCreated sql.NullInt64
	AccountID      string
	LastActivity   sql.NullInt64
}

func (q *Queries) GetUserBySession(ctx context.Context, sessionID sql.NullString) (GetUserBySessionRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBySession, sessionID)
	var i GetUserBySessionRow
	err := row.Scan(
		&i.Username,
		&i.Pwhash,
		&i.SessionID,
		&i.SessionCreated,
		&i.AccountID,
		&i.LastActivity,
	)
	return i, err
}

const getUserByShareToken = `-- name: GetUserByShareToken :one
SELECT username, account_id, share_token FROM users WHERE share_token = $1
`

type GetUserByShareTokenRow struct {
	Username   string
	AccountID  string
	ShareToken sql.NullString
}

func (q *Queries) GetUserByShareToken(ctx context.Context, shareToken sql.NullString) (GetUserByShareTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByShareToken, shareToken)
	var i GetUserByShareTokenRow
	err := row.Scan(&i.Username, &i.AccountID, &i.ShareToken)
	return i, err
}

const listAPIKeysByAccount = `-- name: ListAPIKeysByAccount :many
SELECT id, account_id, name, prefix, role, created_at, last_used FROM api_keys WHERE account_id = $1 ORDER BY created_at DESC
`

type ListAPIKeysByAccountRow struct {
	ID        string
	AccountID string
	Name      string
	Prefix    string
	Role      string
	CreatedAt int64
	LastUsed  sql.NullInt64
}

func (q *Queries) ListAPIKeysByAccount(ctx context.Context, accountID string) ([]ListAPIKeysByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByAccountRow
	for rows.Next() {
		var i ListAPIKeysByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Prefix,
			&i.Role,
			&i.CreatedAt,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.username, a.role, a.created_at, a.last_login,
       (SELECT COUNT(*) FROM users u WHERE u.account_id = a.id) AS user_count,
       COALESCE((SELECT MAX(u.last_activity) FROM users u WHERE u.account_id = a.id), 0) AS last_activity
FROM accounts a
ORDER BY a.username
`

type ListAccountsRow struct {
	ID           string
	Username     string
	Role         string
	CreatedAt    int64
	LastLogin    sql.NullInt64
	UserCount    int64
	LastActivity interface{}
}

func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
			&i.LastLogin,
			&i.UserCount,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many
SELECT id, username, caption, type, last_activity FROM devices WHERE username = $1
`

// Devices
func (q *Queries) ListDevices(ctx context.Context, username string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Caption,
			&i.Type,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInactiveAccounts = `-- name: ListInactiveAccounts :many
SELECT a.id, a.username, a.role, a.created_at
FROM accounts a
WHERE a.role != 'admin'
  AND COALESCE(
    (SELECT MAX(u.last_activity) FROM users u WHERE u.account_id = a.id),
    a.created_at
  ) < $1
`

type ListInactiveAccountsRow struct {
	ID        string
	Username  string
	Role      string
	CreatedAt int64
}

func (q *Queries) ListInactiveAccounts(ctx context.Context, lastActivity sql.NullInt64) ([]ListInactiveAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listInactiveAccounts, lastActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInactiveAccountsRow
	for rows.Next() {
		var i ListInactiveAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.username, u.account_id, a.username AS account_name
FROM users u
JOIN accounts a ON a.id = u.account_id
ORDER BY u.username
`

type ListUsersRow struct {
	Username    string
	AccountID   string
	AccountName string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.Username, &i.AccountID, &i.AccountName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByAccount = `-- name: ListUsersByAccount :many
SELECT username, account_id, last_activity FROM users WHERE account_id = $1 ORDER BY username
`

type ListUsersByAccountRow struct {
	Username     string
	AccountID    string
	LastActivity sql.NullInt64
}

func (q *Queries) ListUsersByAccount(ctx context.Context, accountID string) ([]ListUsersByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByAccountRow
	for rows.Next() {
		var i ListUsersByAccountRow
		if err := rows.Scan(&i.Username, &i.AccountID, &i.LastActivity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByAccountWithStats = `-- name: ListUsersByAccountWithStats :many
SELECT u.username, u.account_id, u.last_activity,
       (SELECT COUNT(*) FROM devices d WHERE d.username = u.username) AS device_count,
       (SELECT COUNT(*) FROM subscriptions s WHERE s.username = u.username AND s.deleted IS NULL) AS subscription_count
FROM users u
WHERE u.account_id = $1
ORDER BY u.username
`

type ListUsersByAccountWithStatsRow struct {
	Username          string
	AccountID         string
	LastActivity      sql.NullInt64
	DeviceCount       int64
	SubscriptionCount int64
}

func (q *Queries) ListUsersByAccountWithStats(ctx context.Context, accountID string) ([]ListUsersByAccountWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByAccountWithStats, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByAccountWithStatsRow
	for rows.Next() {
		var i ListUsersByAccountWithStatsRow
		if err := rows.Scan(
			&i.Username,
			&i.AccountID,
			&i.LastActivity,
			&i.DeviceCount,
			&i.SubscriptionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateSubscription = `-- name: ReactivateSubscription :exec
UPDATE subscriptions SET created = $1, deleted = NULL
WHERE username = $2 AND url = $3 AND deleted IS NOT NULL
`

type ReactivateSubscriptionParams struct {
	Created  int64
	Username string
	Url      string
}

func (q *Queries) ReactivateSubscription(ctx context.Context, arg ReactivateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, reactivateSubscription, arg.Created, arg.Username, arg.Url)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used = $1 WHERE id = $2
`

type UpdateAPIKeyLastUsedParams struct {
	LastUsed sql.NullInt64
	ID       string
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, arg.LastUsed, arg.ID)
	return err
}

const updateAccountLastLogin = `-- name: UpdateAccountLastLogin :exec
UPDATE accounts SET last_login = $1 WHERE id = $2
`

type UpdateAccountLastLoginParams struct {
	LastLogin sql.NullInt64
	ID        string
}

func (q *Queries) UpdateAccountLastLogin(ctx context.Context, arg UpdateAccountLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountLastLogin, arg.LastLogin, arg.ID)
	return err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :exec
UPDATE accounts SET pwhash = $1 WHERE id = $2
`

type UpdateAccountPasswordParams struct {
	Pwhash string
	ID     string
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountPassword, arg.Pwhash, arg.ID)
	return err
}

const updateAccountRole = `-- name: UpdateAccountRole :exec
UPDATE accounts SET role = $1 WHERE id = $2
`

type UpdateAccountRoleParams struct {
	Role string
	ID   string
}

func (q *Queries) UpdateAccountRole(ctx context.Context, arg UpdateAccountRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountRole, arg.Role, arg.ID)
	return err
}

const updateAccountSession = `-- name: UpdateAccountSession :exec
UPDATE accounts SET session_id = $1, session_created = $2 WHERE id = $3
`

type UpdateAccountSessionParams struct {
	SessionID      sql.NullString
	SessionCreated sql.NullInt64
	ID             string
}

func (q *Queries) UpdateAccountSession(ctx context.Context, arg UpdateAccountSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountSession, arg.SessionID, arg.SessionCreated, arg.ID)
	return err
}

const updateAccountUsername = `-- name: UpdateAccountUsername :exec
UPDATE accounts SET username = $1 WHERE id = $2
`

type UpdateAccountUsernameParams struct {
	Username string
	ID       string
}

func (q *Queries) UpdateAccountUsername(ctx context.Context, arg UpdateAccountUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountUsername, arg.Username, arg.ID)
	return err
}

const updateDeviceCaption = `-- name: UpdateDeviceCaption :exec
UPDATE devices SET caption = $1 WHERE id = $2 AND username = $3
`

type UpdateDeviceCaptionParams struct {
	Caption  sql.NullString
	ID       string
	Username string
}

func (q *Queries) UpdateDeviceCaption(ctx context.Context, arg UpdateDeviceCaptionParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceCaption, arg.Caption, arg.ID, arg.Username)
	return err
}

const updateDeviceLastActivity = `-- name: UpdateDeviceLastActivity :exec
UPDATE devices SET last_activity = $1 WHERE id = $2 AND username = $3
`

type UpdateDeviceLastActivityParams struct {
	LastActivity sql.NullInt64
	ID           string
	Username     string
}

func (q *Queries) UpdateDeviceLastActivity(ctx context.Context, arg UpdateDeviceLastActivityParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceLastActivity, arg.LastActivity, arg.ID, arg.Username)
	return err
}

const updateDeviceType = `-- name: UpdateDeviceType :exec
UPDATE devices SET type = $1 WHERE id = $2 AND username = $3
`

type UpdateDeviceTypeParams struct {
	Type     string
	ID       string
	Username string
}

func (q *Queries) UpdateDeviceType(ctx context.Context, arg UpdateDeviceTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceType, arg.Type, arg.ID, arg.Username)
	return err
}

const updateUserLastActivity = `-- name: UpdateUserLastActivity :exec
UPDATE users SET last_activity = $1 WHERE username = $2
`

type UpdateUserLastActivityParams struct {
	LastActivity sql.NullInt64
	Username     string
}

func (q *Queries) UpdateUserLastActivity(ctx context.Context, arg UpdateUserLastActivityParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastActivity, arg.LastActivity, arg.Username)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET pwhash = $1 WHERE username = $2
`

type UpdateUserPasswordParams struct {
	Pwhash   string
	Username string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Pwhash, arg.Username)
	return err
}

const updateUserSession = `-- name: UpdateUserSession :exec
UPDATE users SET session_id = $1, session_created = $2 WHERE username = $3
`

type UpdateUserSessionParams struct {
	SessionID      sql.NullString
	SessionCreated sql.NullInt64
	Username       string
}

func (q *Queries) UpdateUserSession(ctx context.Context, arg UpdateUserSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSession, arg.SessionID, arg.SessionCreated, arg.Username)
	return err
}

const updateUserShareToken = `-- name: UpdateUserShareToken :exec
UPDATE users SET share_token = $1 WHERE username = $2
`

type UpdateUserShareTokenParams struct {
	ShareToken sql.NullString
	Username   string
}

func (q *Queries) UpdateUserShareToken(ctx context.Context, arg UpdateUserShareTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateUserShareToken, arg.ShareToken, arg.Username)
	return err
}

const upsertEpisode = `-- name: UpsertEpisode :exec
INSERT INTO episodes (username, device, podcast, episode, timestamp, guid, action, started, position, total, modified, content_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT(username, podcast, episode) DO UPDATE SET
    device = EXCLUDED.device,
    timestamp = EXCLUDED.timestamp,
    guid = EXCLUDED.guid,
    action = EXCLUDED.action,
    started = EXCLUDED.started,
    position = EXCLUDED.position,
    total = EXCLUDED.total,
    modified = CASE WHEN EXCLUDED.content_hash != episodes.content_hash THEN EXCLUDED.modified ELSE episodes.modified END,
    content_hash = EXCLUDED.content_hash
`

type UpsertEpisodeParams struct {
	Username    string
	Device      sql.NullString
	Podcast     string
	Episode     string
	Timestamp   sql.NullInt64
	Guid        sql.NullString
	Action      string
	Started     sql.NullInt64
	Position    sql.NullInt64
	Total       sql.NullInt64
	Modified    int64
	ContentHash string
}

func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, upsertEpisode,
		arg.Username,
		arg.Device,
		arg.Podcast,
		arg.Episode,
		arg.Timestamp,
		arg.Guid,
		arg.Action,
		arg.Started,
		arg.Position,
		arg.Total,
		arg.Modified,
		arg.ContentHash,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value) VALUES ($1, $2)
ON CONFLICT(key) DO UPDATE SET value = EXCLUDED.value
`

type UpsertSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
